apiVersion: v1
kind: Namespace
metadata:
  name: nginx  # 생성할 네임스페이스 이름
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx  # 앞서 생성한 nginx 네임스페이스에 배포
  labels:
    app: nginx
spec:
  replicas: 1  # 원하는 복제본 수
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        group: worker1  # worker1 노드에 배포
      imagePullSecrets:
        - name: regcred  # 이미지 풀 시 사용하는 Secret 이름
      containers:
        - name: nginx
          image: 200.0.1.250/cudo/nginx:latest
          ports:
            - containerPort: 80  # nginx 기본 포트
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx  # nginx 네임스페이스에 서비스 생성
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # 외부에서 접근할 포트
      targetPort: 80  # 컨테이너 내에서 노출할 포트
      nodePort: 31000  # 외부 접근용 포트 38000
  type: NodePort  # NodePort 서비스

